version: "3.8"
name: maze-solver

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - 5000:5000
    restart: on-failure
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - backend
networks:
  default:
    name: maze-solver