POST http://localhost:{{$dotenv PORT}}/bfs HTTP/1.1
content-type: application/json

{
    "maze": "########E#######\n#..........#...#\n#.######.###.#.#\n#.##...#..##.#.#\n#....#..##.....#\n##.#.########.##\n##.#.....S.....#\n################"
}